### ISSUE TITLE
Thanks for forking my package :thumbs-up:

### ISSUE THREAD

**Issue by bashleigh** [fenos/nestjs-config#1]
Thanks for forking my package then redistributing it.

**Comment by fenos** [comment]
@bashleigh Hi there,

I'm Sorry to hear that from you.
I was looking for a config package for NestJS and the only one I found was yours.

Although I didn't like the approach you took.
You are using the [FULL](https://github.com/bashleigh/nest-config/blob/master/src/ConfigModule/config.service.ts#L9
) `process.env` as the config object.

So, I initially forked your package with the will of making few PR. 
But then, no tests were there and the package looked minimalistic to me. 

So i though todo a different version of the `nestjs-config` which **works in a totally different way** then your package. 

Is not a copy is a re-implementation with different usage. 

Do you want to join forces? I'll be glad to move this code to your repository if you like my approach to configs. 

Probaly you haven't even **READ** the source code before opening this issue.

**Comment by bashleigh** [comment]
I did want to keep it quite basic as the project has a simple task. I also haven't had a lot of time to dedicate to it and thought "it works, don't fix it". I too hate the fact that I used `process.env()` and I do prefer your way of using config files, it does look a lot like laravel that way and I'm used to using it that way too. 
Ultimately your way would enable functions and callbacks to modify ENVs before returning them. 

I would like to join forces yes, I have just suggested to nestjs that the repo gets transferred to them. https://github.com/nestjs/docs.nestjs.com/issues/112

I'm also going to try and add some decorators to the repo to provider better support like so 

```ts
@Controller()
@Configurable() //needs a better name I think
export default UserController {
  async test(@ConfigParam('APP_TEST', 'default') test) {
    return test;
  }
}
```

I did also read the source this morning, I did find it quite similar including the use of my name in the LICENSE and the InjectConfig decorator.

**Comment by bashleigh** [comment]
Also, your tests are pretty cool. Feel like I can't add them to my repo now or I'll look like I'm copying you 😂

**Comment by bashleigh** [comment]
I've also got a nest-amqp package that I could do with some help with. I was thinking of adding jest along with a dockerfile for a rabbitmq container

**Comment by fenos** [comment]
Thanks for your reply.

That is exactly why I made up this package. 

I have nothing against you, neither I wanted to steal your package. 

I’m used to use configuration in this way too, as you said “the laravel way 😄”

Yes, I copied the licence and the decorators from your repo. 

The decorators were really well thought. Regarding the Licence 😳 I’ve been lazy To generate one I’ll amend it. I’m very sorry about that.

Yhea, the public api methods are the same.
It’s hard to find a better name for them. The implementation defer from yours, ex: using loadash.get / set.

Please go ahead and copy my tests I really don’t mind, we are a community to make software better if my code helps it’s there for you’ve to reuse that’s why we use MIT license 🎉

Cool I’m glad you want join forces. I want the same here. 

Your issue title and description has been a little harsh to me.

**Comment by fenos** [comment]
You had Great idea for the decorators. 

Also I’ll be happy to check your package out. Nest-ampq I promise I’ll not create another one 👍😆

**Comment by bashleigh** [comment]
It's happened now, sorry it was a bit negative, I was pretty angry last night and didn't sleep that much because I was angry because I'm a saddo. 

Going forward though, if nestjs accepts the re-ownership we can both contribute there and improve the package together. Else do you want to make a singular repo and rename the package to `nestjs-config` rather than `'@bashleigh/nest-config'`. What'd you think about that? Could even make an organisation and transfer both `nestjs-config` and `nest-amqp` to the organisation. although I think the AMQP one needs a LOT more work and thought put into it. I've made it 'useable' for work at the moment but I again wanted to add some cool decorators to it to make it usable much like the controller decorator. 

Sorry again for being an angry prick!

**Comment by fenos** [comment]
> It's happened now, sorry it was a bit negative, I was pretty angry last night and didn't sleep that much because I was angry because I'm a saddo.

Oh Dear, sorry to hear that I'll promise we'are going to fix this and you'll be sleeping very well tonight.

> Going forward though, if nestjs accepts the re-ownership we can both contribute there and improve the package together. Else do you want to make a singular repo and rename the package to nestjs-config rather than '@bashleigh/nest-config'. What'd you think about that? Could even make an organisation and transfer both nestjs-config and nest-amqp to the organisation. although I think the AMQP one needs a LOT more work and thought put into it. I've made it 'useable' for work at the moment but I again wanted to add some cool decorators to it to make it usable much like the controller decorator.

Yes, going forward I'll be happy to either the 3 solutions you proposed.

- NestJS approving this as an official repo. So we both contribute there.
- Open an organisation as you suggested, for community maintained NestJS packages. (I really like this).
- I'll make a PR with the full code of this repo to your own repo package, but you'll need to rename it to `nestjs-config` and I'll transfer the npm ownership. 
I like this too. Because you seemed to appreciate the approach i had for Nest configuration. 
I'll be a contributor there.

Let me know which one you prefer, I really don't mind 🎉  as far I can use this package in my code. I Don't mind where it lives 😄

**Comment by bashleigh** [comment]
It's alright, I've been having family problems too and I kinda took it out on you. 

I reckon nest would take a few days to get back to us to be honest. If not a week or so. If we don't hear anything or get rejected then we'll make an organisation if that's cool with you. 
I think since you forked this I merged in some changes for src and root so you can get dirs like laravel ;) (been so long since I jumped on the TS train I can't remember) `public_path('')` I made similar to `config.root('dir/name/file.txt')` which could be improved again to use `path.resolve()`. Which would be cool for pug/jade and app setup configs in the starter repos so that this https://docs.nestjs.com/techniques/mvc becomes: 

```ts
import { NestFactory } from '@nestjs/core';
import { join } from 'path';
import { ApplicationModule } from './app.module';
import {ConfigService} from 'nestjs-config';

async function bootstrap() {
  const app = await NestFactory.create(ApplicationModule);
  const config = app.get(ConfigService);

  app.useStaticAssets(config.root('public'));
  app.setBaseViewsDir(config.root('templates')); //could even do config.templates(); but dunno if I like that? Seeing as the dir is not included in the starter 
  app.setViewEngine(config.get('TEMPLATE_ENGINE', 'pug'));

  await app.listen(config.get('EXPRESS_PORT', 3000)); // express.port in your version :p
}
bootstrap();
```

Is that rename the repo to `nestjs-config` and the package name to `nestjs-config`? 

I'm not too fussed either. I just saw the notification on Saturday for a fork and then saw a root commit so I was like :O feelings!! lol

**Comment by bashleigh** [comment]
Plus I'll have someone to review my PRs :O FRIENDDDDDD!!!

**Comment by fenos** [comment]
> I reckon nest would take a few days to get back to us, to be honest. If not a week or so. If we don't hear anything or get rejected then we'll make an organisation if that's cool with you.

Ok, I'll make a PR to your repo with all of the code of this repo. 
We'll then also need to set up again, `TravisCI` for running tests and `Coveralls` for testing coverage, once merged in.

Probably is better if we have a different way of coordinating this, maybe a slack channel or similar? 

I'm now at work, so I'm not being able to do that till this evening, as soon as I get home you'll have it. 

> Plus I'll have someone to review my PRs :O FRIENDDDDDD!!!

Sure, Any time 😄

**Comment by bashleigh** [comment]
I can setup a slack channel :) dunno what to call it nor the organisation if we need one. Trying not to go with "Friends of nestjs" like "Friends Of Symfony"... ...makes me cringe slightly; FOSUserBundle... ...brings back nightmares. 

Made a PR already, couldn't add you to the review 👎 https://github.com/bashleigh/nest-config/pull/5

I can give setting up the testing a go, I've used jenkins for testing etc but never really set it up. I've not got a lot on this week by the looks of it? So I could contribute a bit today.

**Comment by fenos** [comment]
@bashleigh Call it NestJS - Community. For now. Later on, we can change it.

I'll close this issue for now. Please answer back here with the slack channel so that this evening we can do some work together.

**Comment by bashleigh** [comment]
I created the slack channel and invited you :) I used the email address on the repo. We can change the name of it later
